blank_issues_enabled: false
contact_links:
  - name: Questions or Clarification
    url: https://github.com/thelonewolf39/nationalshutdowngraphics/discussions
    about: Please use Discussions for questions instead of Issues.
